### PR TITLE
Regression: report failures from failed tests instead of errors

### LINKED ISSUE #761: [Regression] JUnit 5/6: Arquillian tests report errors instead of failures
Arquillian tests report all assertion failures as errors:
```
[INFO] --- failsafe:3.5.4:integration-test (integration-test) @ arq-error ---
[INFO] Tests will run in random order. To reproduce ordering use flag -Dfailsafe.runOrder.random.seed=790998900429250
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.reproducers.arq.err.its.StarterIT
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.177 s <<< FAILURE! -- in com.reproducers.arq.err.its.StarterIT
[ERROR] com.reproducers.arq.err.its.StarterIT.sanityCheck -- Time elapsed: 0.149 s <<< ERROR!
IdentifiedTestException [collectedExceptions={[engine:junit-jupiter]/[class:com.reproducers.arq.err.its.StarterIT]/[method:sanityCheck()]=org.opentest4j.AssertionFailedError: 
Expecting value to be true but was false}]
... stack trace ...
```

This is wrong. Unexpected failures and errors should be separated, so failsafe plugin reports them correctly.

According to ChatGPT, there is a minor difference between errors and failures:
> In JUnit Platform (JUnit 5), both "failed" and "errored" tests are represented by the TestExecutionResult.Status.FAILED status. JUnit does not distinguish between assertion failures and unexpected exceptions at the engine level—both are considered "failed".
To differentiate them in an extension, inspect the Throwable in TestExecutionResult.getThrowable():
If the throwable is an AssertionError, it's a test failure (assertion failed).
If it's any other exception, it's an error (unexpected exception).
Example:
```
if (result.getStatus() == TestExecutionResult.Status.FAILED) {
    Throwable throwable = result.getThrowable().orElse(null);
    if (throwable instanceof AssertionError) {
        // Test failed (assertion failed)
    } else {
        // Test errored (unexpected exception)
    }
}
```
This approach lets you distinguish between assertion failures and other errors in your JUnit extension.

### PR DESCRIPTION
**Pull request by lprimak**
#### Short description of what this resolves:
This PR fixes a regression that reports test failures as errors.

Regressed by #727 
Fixes #761 

## Summary by Sourcery

Refactor JUnit5 extension error handling to differentiate assertion failures and other exceptions, ensuring failed tests are reported as failures rather than errors.

Bug Fixes:
- Treat assertion errors as test failures instead of throwing them
- Propagate non-assertion exceptions directly instead of wrapping them

Enhancements:
- Add throwError method to TestResult to centralize failure vs error logic
- Update interceptTestMethod and interceptTestTemplateMethod to use throwError

### CODE REVIEW

File: junit5/core/src/main/java/org/jboss/arquillian/junit5/ArquillianExtension.java [hunk 1]
```diff
@@ -364,4 +354,32 @@ private static ParameterResolutionException createParameterResolutionException(f
...
+            }
+        }
+    }
+
+    private static AssertionFailedError failedAssertion(Throwable exception) {
+        if (exception instanceof IdentifiedTestException) {
+            IdentifiedTestException identified = (IdentifiedTestException) exception;
+            Collection<Throwable> exceptions = identified.getCollectedExceptions().values();
+            if (exceptions.stream().allMatch(AssertionFailedError.class::isInstance)) {
+                return exceptions.stream().filter(AssertionFailedError.class::isInstance)
```
Comment (jamezp) [inline junit5/core/src/main/java/org/jboss/arquillian/junit5/ArquillianExtension.java]: Any reason why in these checks we shouldn't just be checking for a `java.lang.AssertionError`?

File: junit5/core/src/main/java/org/jboss/arquillian/junit5/ArquillianExtension.java [hunk 2]
```diff
@@ -364,4 +354,32 @@ private static ParameterResolutionException createParameterResolutionException(f
...
+                    .map(AssertionFailedError.class::cast)
+                    .findFirst().orElse(null);
+            }
+        }
+        return null;
+    }
```
Comment (jamezp) [inline junit5/core/src/main/java/org/jboss/arquillian/junit5/ArquillianExtension.java]: I think this should be something more like:
```java
private static void throwError(final TestResult result) throws Throwable {
    if (result == null || result.getStatus() == TestResult.Status.PASSED) {
        return;
    }
    if (result.getStatus() == TestResult.Status.SKIPPED) {
        throw new TestAbortedException(result.getDescription());
    }
    if (result.getStatus() == TestResult.Status.FAILED) {
        throw failedAssertion(result.getThrowable()).orElseGet(() -> {
            if (result.getThrowable() != null) {
                return result.getThrowable();
            }
            return new AssertionError(result.getDescription());
        });
    }
    // We should not reach this, but it's a safeguard in case a new status is ever added and missed here
    throw new AssertionError(result.getDescription());
}

private static Optional<Throwable> failedAssertion(Throwable exception) {
    if (exception instanceof IdentifiedTestException) {
        IdentifiedTestException identified = (IdentifiedTestException) exception;
        Collection<Throwable> exceptions = identified.getCollectedExceptions().values();
        if (exceptions.stream().allMatch(AssertionError.class::isInstance)) {
            return exceptions.stream().filter(AssertionError.class::isInstance)
                .findFirst();
        }
    }
    return Optional.empty();
}
```

There is a possibility that `Status.SKIPPED` could have an exception. IMO it's better to explicitly check this.

I think we should be more generic too and look for `java.lang.AssertionError` too.

**Review by jamezp — APPROVED** [review]
