### PR TITLE
fix(jakarta): introduces locks to avoid race conditions

### LINKED ISSUE #319: Race conditions in ServletMethodExecutor when doing parallel testing
##### Issue Overview

Minor race condition discovered that causes `503 Service Unavailable` stack trace
in `org.jboss.arquillian.protocol.servlet(5).ServletMethodExecutor` class

The issue is that when timer is canceled, an already-running timer can hit an application
that was already undeployed.

##### Additional Information

PR is coming to fix this.
Fix testing with MicroProfile SDK

### PR DESCRIPTION
**Pull request by lprimak**
Fixes #319 

added locks and signalling to correctly cancel timers so no stale ope…rations

are called to undeployed applications

### CODE REVIEW

**Comment by lprimak** [comment]
Payara JIRA QACI-638

File: protocols/servlet/src/main/java/org/jboss/arquillian/protocol/servlet/ServletMethodExecutor.java [hunk 1]
```diff
@@ -214,6 +231,8 @@ public void run() {
                     }
                 } catch (Exception e) {
                     e.printStackTrace();
```
Comment (bartoszmajsak) [inline protocols/servlet/src/main/java/org/jboss/arquillian/protocol/servlet/ServletMethodExecutor.java:233]: I find this a little bit concerning, but that's not part of this PR anyway ;)

**Review by bartoszmajsak — APPROVED** [review]
LGTM, thanks for this fix!
