### PR TITLE
fix: improves method name handling executors

### LINKED ISSUE #214: Support JUnit compatible testing frameworks for which FrameworkMethod.getName() != FrameworkMethod.getMethod().getName() and which allow test method names with reserved url characters
##### Issue Overview

Currently, `ServletMethodExecutor` and the `TestMethodExecutor` implementation in `org.jboss.arquillian.junit.MethodInvoker` assume that ` FrameworkMethod.getName() == FrameworkMethod.getMethod().getName()`. [This is indeed the case for JUnit](https://github.com/junit-team/junit4/blob/64155f8a9babcfcf4263cf4d08253a1556e75481/src/main/java/org/junit/runners/model/FrameworkMethod.java#L59:L61) but is not for other JUnit compatible test frameworks like [Spock](http://spockframework.org/). Spock allows whitespace in test names (which are obviously not allowed in method names in jvm bytecode) by [overriding `FrameworkMethod.getName()`](https://github.com/spockframework/spock/blob/e85e79c8eff8b91e173bec65a68a1f7e1d2d2f3b/spock-core/src/main/java/org/spockframework/runtime/extension/builtin/MethodRuleInterceptor.java#L46:L48).

A secondary issue is that `ServletMethodExecutor` expects there to be no reserved url characters in test method names and does not escape them in the urls that it composes but Spock allows them and, what's more, it is common practice to use them, especially spaces.

##### Expected Behaviour

Arquillian works with Spock out of the box for a basic specification using `ArquillianTestClass` and `ArquillianTest` rules:

```
import org.jboss.arquillian.junit.ArquillianTest
import org.jboss.arquillian.junit.ArquillianTestClass
import org.junit.ClassRule
import org.junit.Rule
import spock.lang.Shared
import spock.lang.Specification

class ArquillianSpecification extends Specification {

    @ClassRule
    @Shared
    ArquillianTestClass arquillianTestClass

    @Rule
    ArquillianTest arquillianTest

    def test() {
        expect:
        true
    }
}
```

##### Current Behaviour

The following exception is raised inside of the container when running the specification:

```
java.lang.Exception: No tests found matching Method $spock_feature_0_0(com.example.arquillian.spock.ArquillianSpecification) from org.junit.internal.requests.ClassRequest@5aad4517
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:40)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.jboss.arquillian.junit.container.JUnitTestRunner.execute(JUnitTestRunner.java:61)
	at org.jboss.arquillian.protocol.servlet.runner.ServletTestRunner.executeTest(ServletTestRunner.java:139)
	at org.jboss.arquillian.protocol.servlet.runner.ServletTestRunner.execute(ServletTestRunner.java:117)
	at org.jboss.arquillian.protocol.servlet.runner.ServletTestRunner.doGet(ServletTestRunner.java:86)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        ...
```

##### Steps To Reproduce

Steps to reproduce can be derived from the section on expected behaviour

### PR DESCRIPTION
**Pull request by erdi**
#### Short description of what this resolves:

This resolves #214 by adding support for JUnit compatible testing frameworks for which `FrameworkMethod.getName()` != `FrameworkMethod.getMethod().getName()` and which allow test method names with reserved url characters.

#### Changes proposed in this pull request:

- Use the logical and not the actual test method name in `ServletMethodExecutor`
- Escape reserved characters in test method names when composing urls in `ServletMethodExecutor`

#### Additional notes

I understand that this fixes two separate issues but I decided to submit fixes for them as a single PR because I believe that are interrelated. Please let me know if you'd like to have this split into two commits and two PRs.

I believe that changes made are backwards compatible with the only problematic one in my opinion being introduction of `TestMethodExecutor.getMethodName()`. Ideally it would be added as a default method but Arquillian is still Java 6 compatible so it's not possible. I'm not sure if users are expected to have custom `TestMethodExecutor` implementation but if they are then I'm looking forward on suggestions on how this could be implemented without the potentially breaking change.

I have added a test for my changes, tried to keep the changes to minimum and follow the conventions set out in the project. Please do let me know if I missed something and I will gladly apply any necessary changes to this PR.

### CODE REVIEW

File: protocols/servlet/src/main/java/org/jboss/arquillian/protocol/servlet/ServletMethodExecutor.java [hunk 1]
```diff
@@ -75,16 +76,18 @@ public TestResult invoke(final TestMethodExecutor testMethodExecutor) {
...
-            + "?outputMode=serializedObject&className=" + testClass.getName() + "&methodName="
-            + testMethodExecutor.getMethod().getName();
-
-        final String eventUrl = targetBaseURI.toASCIIString() + ARQUILLIAN_SERVLET_MAPPING
-            + "?outputMode=serializedObject&className=" + testClass.getName() + "&methodName="
-            + testMethodExecutor.getMethod().getName() + "&cmd=event";
 
         Timer eventTimer = null;
         try {
+            String urlEncodedMethodName = URLEncoder.encode(testMethodExecutor.getMethodName(), "UTF-8");
```
Comment (erdi) [inline protocols/servlet/src/main/java/org/jboss/arquillian/protocol/servlet/ServletMethodExecutor.java]: I've moved this block of code inside of the try/catch because `URLEncoder.encode()` throws `UnsupportedEncodingException`.

File: protocols/servlet/src/test/java/org/jboss/arquillian/protocol/servlet/ProtocolTestCase.java [hunk 2]
```diff
@@ -50,6 +50,27 @@ public void shouldReturnTestResult() throws Exception {
             result.getThrowable());
     }
 
+    @Test
+    public void shouldUseLogicalMethodNameAndHandleUrlEscaping() throws Exception {
```
Comment (erdi) [inline protocols/servlet/src/test/java/org/jboss/arquillian/protocol/servlet/ProtocolTestCase.java]: This test is actually testing two things - using logical names for test methods and url escaping of test method names in `ServletMethodExecutor`. I was unsure if this should be therefore split into two test or if that would be deemed an overkill. Please let me know what you think.

**Comment by erdi** [comment]
CI failure seems to be unrelated to my changes. Locally I have successfully run the following:

```
./mvnw install -q -U -DskipTests=true
./mvnw clean install
...
[INFO] Reactor Summary for Arquillian Aggregator 1.4.2.Final-SNAPSHOT:
[INFO] 
[INFO] Arquillian Aggregator .............................. SUCCESS [  1.201 s]
[INFO] Arquillian Build ................................... SUCCESS [  0.552 s]
[INFO] Arquillian Core API ................................ SUCCESS [  1.194 s]
[INFO] Arquillian Core SPI ................................ SUCCESS [  0.611 s]
[INFO] Arquillian Core Implementation Base ................ SUCCESS [  1.976 s]
[INFO] Arquillian Core Aggregator ......................... SUCCESS [  0.124 s]
[INFO] Arquillian Config API .............................. SUCCESS [  1.173 s]
[INFO] Arquillian Config SPI .............................. SUCCESS [  0.447 s]
[INFO] Arquillian Test API ................................ SUCCESS [  0.431 s]
[INFO] Arquillian Test SPI ................................ SUCCESS [  1.657 s]
[INFO] Arquillian Test Implementation Base ................ SUCCESS [  1.519 s]
[INFO] Arquillian Config Implementation Base .............. SUCCESS [  3.366 s]
[INFO] Arquillian Config Aggregator ....................... SUCCESS [  0.249 s]
[INFO] Arquillian Test Aggregator ......................... SUCCESS [  0.100 s]
[INFO] Arquillian Container SPI ........................... SUCCESS [  1.497 s]
[INFO] Arquillian Container Implementation Base ........... SUCCESS [  3.230 s]
[INFO] Arquillian Container Test API ...................... SUCCESS [  1.194 s]
[INFO] Arquillian Container Test SPI ...................... SUCCESS [  0.635 s]
[INFO] Arquillian Container Test Implementation Base ...... SUCCESS [  2.406 s]
[INFO] Arquillian Container Aggregator .................... SUCCESS [  0.248 s]
[INFO] Arquillian TestRunner JUnit Core ................... SUCCESS [  3.553 s]
[INFO] Arquillian TestRunner JUnit Standalone ............. SUCCESS [  1.871 s]
[INFO] Arquillian TestRunner JUnit Container .............. SUCCESS [  2.063 s]
[INFO] Arquillian TestRunner JUnit Aggregator ............. SUCCESS [  0.109 s]
[INFO] Arquillian TestRunner TestNG Core .................. SUCCESS [  2.530 s]
[INFO] Arquillian TestRunner TestNG Standalone ............ SUCCESS [  0.453 s]
[INFO] Arquillian TestRunner TestNG Container ............. SUCCESS [  2.312 s]
[INFO] Arquillian TestRunner TestNG Aggregator ............ SUCCESS [  0.118 s]
[INFO] Arquillian TestEnricher CDI ........................ SUCCESS [  3.148 s]
[INFO] Arquillian TestEnricher EJB ........................ SUCCESS [  1.897 s]
[INFO] Arquillian TestEnricher Resource ................... SUCCESS [  1.869 s]
[INFO] Arquillian TestEnricher InitialContext ............. SUCCESS [  0.741 s]
[INFO] Arquillian TestEnricher Aggregator ................. SUCCESS [  0.111 s]
[INFO] Arquillian Protocol Servlet 2.5/3.x ................ SUCCESS [  4.195 s]
[INFO] Arquillian Protocol JMX ............................ SUCCESS [  1.401 s]
[INFO] Arquillian Protocol Aggregator ..................... SUCCESS [  0.114 s]
[INFO] Arquillian BOM ..................................... SUCCESS [  0.237 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  22.297 s (Wall Clock)
[INFO] Finished at: 2019-09-20T13:30:49+01:00
[INFO] ------------------------------------------------------------------------
```

**Comment by bartoszmajsak** [comment]
> CI failure seems to be unrelated to my changes. Locally I have successfully run the following:

Yeah, Travis is getting unreliable lately. Don't worry, I will have a look now.

In parallel, I'm thinking about moving to CircleCI or GH Actions.

**Comment by erdi** [comment]
Thanks for noticing my efforts and finding my contribution valuable. As an [OSS project maintainer myself](https://github.com/geb/geb/graphs/contributors) I always try my best on PRs to other projects so that it's as easy as possible for the maintainers to review. Putting in the effort also increases the chances of the contribution being accepted and in the end the main driver here is to the I'm affected by fixed. :)

File: protocols/servlet/src/test/java/org/jboss/arquillian/protocol/servlet/ProtocolTestCase.java (hunk 2 above)
Comment (erdi) [reply protocols/servlet/src/test/java/org/jboss/arquillian/protocol/servlet/ProtocolTestCase.java]: There are two things that I find not great about explicitly testing that the name is url encoded:
* the URL encoding is currently buried deep in `ServletMethodExecutor.invoke()` so to be able to test it we would need to extract it out from there and I find that quite significant a effort which I'd argue is out of scope of this PR,
* as an Arquillian user I want to verify that if a test method has spaces it will still execute in the container as expected and the fact that it gets URL encoded along the way is more of an implementation detail.

In the lights of the above I'm thinking about changing the name of the test in question to `shouldUseLogicalMethodNameAndSupportUrlReservedCharactersInIt`. What are your views on that?

**Comment by erdi** [comment]
> For the others (and there are not that many I think) - how about we mark the old getMethod @Depracated pointing to why the new one should be used in Javadoc?

Hmmm... I don't quite follow. Why would we want to deprecate `TestMethodExecutor.getMethod()`? I believe it's still needed and rightly so. It still has it's use, in `org.jboss.arquillian.container.test.impl.execution.LocalTestExecuter#execute` for example as well as in `org.jboss.arquillian.protocol.servlet.ServletMethodExecutor#invoke` which passes the result to `org.jboss.arquillian.protocol.servlet.ServletURIHandler#locateTestServlet()`. Would you disagree?

Btw, I've noticed a couple of issues in this PR (two implementations of `TestMethodExecutor.getMethodName()` are incorrect and in some places `TestMethodExecutor.getMethod().getName()` is still used instead of `TestMethodExecutor.getMethodName()`). I'd therefore like to push an additional commit to this branch but you've already merged master into it. Would you be ok with me adding a commit, dropping your merge commits and rebasing my branch onto the top of current master?

**Comment by bartoszmajsak** [comment]
> Hmmm... I don't quite follow. Why would we want to deprecate TestMethodExecutor.getMethod()? I believe it's still needed and rightly so

Correct, I think I was a bit too fast.

>  I'd therefore like to push an additional commit to this branch but you've already merged master into it. Would you be ok with me adding a commit, dropping your merge commits and rebasing my branch onto the top of current master?

I think you can simply add another commit and I will take care of bringing those changes back to master, don't worry about that.

File: protocols/servlet/src/test/java/org/jboss/arquillian/protocol/servlet/ProtocolTestCase.java (hunk 2 above)
Comment (bartoszmajsak) [reply protocols/servlet/src/test/java/org/jboss/arquillian/protocol/servlet/ProtocolTestCase.java]: I agree that doing an explicit check can result in scope creep for this PR, hence to do it right we would need to refactor the whole thing. I think the rename is giving a bit of a hint for the intent of the test, so that is fine with me.

**Comment by erdi** [comment]
Ok, I believe I have addressed all of your comments, over to you, @bartoszmajsak.
